### ISSUE TITLE
AplicacionDeHilos

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-equipo_eaaj#1]
[practica8visual.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-equipo_eaaj/files/15119226/practica8visual.pdf)

**Comment by AricelCastro** [comment]
19/20 falto mas imagenes y conclusion

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
